version: "3.7"

services:

  logging:
    container_name: nnn-logging
    build: ./logging
    ports:
      - "12201:12201/udp"
    environment:
      PORT: 12201
      APPINSIGHTS_INSTRUMENTATIONKEY: /run/secrets/APPINSIGHTS_INSTRUMENTATIONKEY
    secrets:
      - APPINSIGHTS_INSTRUMENTATIONKEY
    restart: always
    entrypoint: /var/logging/start.sh

  db:
    container_name: nnn-db
    build: ./db
    depends_on:
      - logging
    networks:
      - nnn-network
    ports:
      - "27017:27017"
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://localhost:12201"
    environment:
      MONGO_INITDB_DATABASE: nnn
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/MONGO_INITDB_ROOT_USERNAME_FILE
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/MONGO_INITDB_ROOT_PASSWORD_FILE
      WEB_NNN_PASSWORD_FILE: /run/secrets/WEB_NNN_PASSWORD_FILE
    secrets:
      - MONGO_INITDB_ROOT_USERNAME_FILE
      - MONGO_INITDB_ROOT_PASSWORD_FILE
      - WEB_NNN_PASSWORD_FILE
    restart: always
    privileged: true
    volumes:
      - db-data:/data/db:rw

  redis:
    container_name: nnn-redis
    build: ./redis
    depends_on:
      - logging
    networks:
      - nnn-network
    ports:
      - "6379:6379"
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://localhost:12201"
    environment:
      REDIS_PASSWORD_FILE: /run/secrets/REDIS_PASSWORD_FILE
      REDIS_PORT: 6379
    secrets:
      - REDIS_PASSWORD_FILE
    restart: always
    entrypoint: /var/redis/start.sh
    privileged: true

  node:
    container_name: nnn-node
    build: ./node
    depends_on:
      - logging
    networks:
      - nnn-network
    ports:
      - "3030:3030"
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://localhost:12201"
    environment:
      APPINSIGHTS_INSTRUMENTATIONKEY: /run/secrets/APPINSIGHTS_INSTRUMENTATIONKEY
      DEFAULT_TIMEZONE: America/Los_Angeles
      DISCORD_ADMIN_USERNAME: roncli
      DISCORD_ADMIN_DISCRIMINATOR: 1409
      DISCORD_GUILD: Noita Nemesis Nation
      DISCORD_TOKEN_FILE: /run/secrets/DISCORD_TOKEN_FILE
      DOMAIN: nnn.roncli.com
      MINIFY_CACHE: 1
      MINIFY_ENABLED: 1
      NNN_DISCORD_URL: https://ronc.li/nnn-discord
      NODE_ENV: production
      PORT: 3030
      REDIS_ENABLED: 1
      REDIS_PASSWORD_FILE: /run/secrets/REDIS_PASSWORD_FILE
      REDIS_PORT: 6379
      REDIS_PREFIX: nnn
      WEB_NNN_PASSWORD_FILE: /run/secrets/WEB_NNN_PASSWORD_FILE
    secrets:
      - APPINSIGHTS_INSTRUMENTATIONKEY
      - DISCORD_TOKEN_FILE
      - REDIS_PASSWORD_FILE
      - WEB_NNN_PASSWORD_FILE
    restart: always
    entrypoint: /var/www/start.sh
    privileged: true

  nginx:
    container_name: nnn-nginx
    build: ./nginx
    depends_on:
      - node
      - logging
    networks:
      - nnn-network
    ports:
      - "80:80"
      - "443:443"
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://localhost:12201"
    environment:
      DOMAIN: nnn.roncli.com
      PROXY_PORT: 3030
    restart: always
    volumes:
      - certbot-conf:/etc/letsencrypt:rw
      - certbot-work:/var/certbot/work:rw
      - nginx-work:/var/nginx/work:rw
    entrypoint: /var/nginx/start.sh

  certbot:
    container_name: nnn-certbot
    build: ./certbot
    depends_on:
      - nginx
      - logging
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://localhost:12201"
    environment:
      DOMAIN: nnn.roncli.com
      EMAIL: roncli@roncli.com
    restart: always
    volumes:
      - certbot-conf:/etc/letsencrypt:rw
      - certbot-work:/var/certbot/work:rw
    entrypoint: /var/certbot/start.sh

networks:
  nnn-network:
    driver: bridge

volumes:
  certbot-conf:
  certbot-work:
  db-data:
  nginx-work:

secrets:
  APPINSIGHTS_INSTRUMENTATIONKEY:
    file: ./secrets/APPINSIGHTS_INSTRUMENTATIONKEY
  DISCORD_TOKEN_FILE:
    file: ./secrets/DISCORD_TOKEN_FILE
  MONGO_INITDB_ROOT_PASSWORD_FILE:
    file: ./secrets/MONGO_INITDB_ROOT_PASSWORD_FILE
  MONGO_INITDB_ROOT_USERNAME_FILE:
    file: ./secrets/MONGO_INITDB_ROOT_USERNAME_FILE
  REDIS_PASSWORD_FILE:
    file: ./secrets/REDIS_PASSWORD_FILE
  WEB_NNN_PASSWORD_FILE:
    file: ./secrets/WEB_NNN_PASSWORD_FILE
